{
 "title": "Spectrum Scale File System Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fs", "label": "File System", "query": "fs0" },
   { "name": "perf", "label": "Performance Metric", "query": "rbytes, wbytes, rops, wops" }
  ]
 },
 "panels": [
  {
   "title": "$fs File System Performance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(sum(\"rbytes\")) / 60 FROM \"gpfsnsdperf\" WHERE $timeFilter and fs='$fs' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(sum(\"wbytes\")) / 60 FROM \"gpfsnsdperf\" WHERE $timeFilter and fs='$fs' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Read IOPs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(sum(\"rops\")) / 60 FROM \"gpfsnsdperf\" WHERE $timeFilter and fs='$fs' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write IOPs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(sum(\"wops\")) / 60 FROM \"gpfsnsdperf\" WHERE  $timeFilter and fs='$fs' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$fs per NSD Server $perf",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(sum(\"$perf\")) / 60 FROM \"gpfsnsdperf\" WHERE (\"fs\" = '$fs') AND $timeFilter GROUP BY time($__interval),node fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$fs NSD Performance Heat Map",
   "type": "heatmap",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "$tag_nsd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(sum(\"$perf\")) / 60 FROM \"gpfsnsdperf\" WHERE (\"fs\" = '$fs') AND $timeFilter GROUP BY time($__interval),nsd fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}