{
 "title": "Spectrum Scale Quota",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fileset",
    "label": "Fileset",
    "query": "SHOW TAG VALUES WITH KEY = \"fileset\""
   },
   {
    "name": "name",
    "label": "Username",
    "query": "SHOW TAG VALUES WITH KEY = \"name\" WHERE \"fileset\" =~ /^$fileset$/ and \"type\" = 'USR'"
   }
  ]
 },
 "panels": [
  {
   "title": "Usage by Fileset",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select blockused from quota where type='FILESET' and $timeFilter group by \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fileset Quota Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select blockused/blockquota from quota where type='FILESET' and $timeFilter group by \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fileset Capacity Consumption Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "quota",
     "query": "SELECT \"blockused\" FROM \"quota\" WHERE (\"type\" = 'FILESET') AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "blockused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "FILESET" }
     ]
    }
   ]
  },
  {
   "title": "Fileset Statistics (Select in Drop Down)",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Fileset Block Usage Trend",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "Used Bytes",
     "measurement": "quota",
     "query": "SELECT \"blockused\" FROM \"autogen\".\"quota\" WHERE (\"fileset\" =~ /^$fileset$/ AND \"type\" = 'FILESET') AND $timeFilter",
     "select": [
      [
       { "params": [ "blockused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" },
      { "condition": "AND", "key": "fileset", "operator": "=~", "value": "/^$fileset$/" }
     ]
    },
    {
     "alias": "Quota Bytes",
     "measurement": "quota",
     "query": "SELECT \"blocklimit\" FROM \"autogen\".\"quota\" WHERE (\"fileset\" =~ /^$fileset$/ AND \"type\" = 'FILESET') AND $timeFilter",
     "select": [
      [
       { "params": [ "blockused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" },
      { "condition": "AND", "key": "fileset", "operator": "=~", "value": "/^$fileset$/" }
     ]
    }
   ]
  },
  {
   "title": "User Usage within Fileset",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"name\",blockused,filesused from quota where type='USR' and fileset =~ /^$fileset$/ and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Fileset Quota",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"blocklimit\") FROM \"autogen\".\"quota\" WHERE (\"fileset\" =~ /^$fileset$/ AND \"type\" = 'FILESET')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "iNodes Used (Fileset Total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"filesused\") FROM \"autogen\".\"quota\" WHERE (\"fileset\" =~ /^$fileset$/ AND \"type\" = 'FILESET')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fileset iNode Usage Trend",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Used iNodes",
     "measurement": "quota",
     "query": "SELECT \"filesused\" FROM \"quota\" WHERE (\"fileset\" =~ /^$fileset$/  AND \"type\" = 'FILESET') AND $timeFilter",
     "select": [
      [
       { "params": [ "filesused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$fileset$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" }
     ]
    },
    {
     "alias": "Max iNodes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"maxinode\" FROM fileset WHERE (\"name\" =~ /^$fileset$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Individual User Statistics Within Fileset (User/Fileset Selected in Drop Down)",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Fileset iNode Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Used iNodes",
     "measurement": "quota",
     "query": "SELECT \"filesused\" FROM \"quota\" WHERE (\"fileset\" =~ /^$fileset$/  AND \"name\" =~ /^$name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "filesused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$fileset$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" }
     ]
    }
   ]
  },
  {
   "title": "Fileset Block Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 26 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "Used Bytes",
     "measurement": "quota",
     "query": "SELECT \"blockused\" FROM \"autogen\".\"quota\" WHERE (\"fileset\" =~ /^$fileset$/ AND \"name\" =~ /^$name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "blockused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" },
      { "condition": "AND", "key": "fileset", "operator": "=~", "value": "/^$fileset$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 14, "y": 26 },
   "options": {
    "content": "Files or Blocks \"In Doubt\" are attributed to files that are still open by processes on the cluster and thus their exact size is not certain due to current operations being performed on these files."
   }
  },
  {
   "title": "Blocks In Doubt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 28 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "quota",
     "query": "SELECT \"blockdoubt\" FROM \"autogen\".\"quota\" WHERE (\"fileset\" =~ /^$fileset$/) AND \"name\" =~ /^$name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "blockdoubt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$fileset$/" }
     ]
    }
   ]
  },
  {
   "title": "Files In Doubt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "quota",
     "query": "SELECT \"filedoubt\" FROM \"autogen\".\"quota\" WHERE ( \"fileset\" =~ /^$fileset$/) AND \"name\" =~ /^$name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "filedoubt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$fileset$/" }
     ]
    }
   ]
  }
 ]
}