{
 "title": "Spectrum Scale NSD Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Inlet Temperature",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select value from ipmi_sensor where \"name\" = 'inlet_temp' and $timeFilter and host =~ /^your_nsd_server_regex[1-6]/ and $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exhaust Temperature",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select value from ipmi_sensor where \"name\" = 'exhaust_temp' and $timeFilter and host =~ /^your_nsd_server_regex[1-6]/ group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select value from ipmi_sensor where \"name\" = 'temp' and $timeFilter and host =~ /^your_nsd_server_regex[1-6]/ group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select value from ipmi_sensor where \"name\" = 'pwr_consumption' and $timeFilter and host =~ /^your_nsd_server_regex[1-6]/ group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Fan Speed",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select value from ipmi_sensor where \"name\" =~ /^fan.*/ and unit='rpm' and host =~ /^your_nsd_server_regex[1-6]/ and $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Input Voltage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select value from ipmi_sensor where \"name\" =~ /^voltage_.*/ and host =~ /^your_nsd_server_regex[1-6]/  and $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NSD Alert State",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Alert State" }
   ],
   "targets": [
    {
     "alias": "$tag_nsdname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select avail_state from mmlsdisk where $timeFilter and fs ='your_fs0_here' group by nsdname",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Multipathd Service Health",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Alert State" }
   ],
   "targets": [
    {
     "alias": "$tag_host Multipathd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select binary_state from services where title='multipathd' and host =~ /^your_nsd_server_regex[1-6].*/ and $timeFilter GROUP BY host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DDN-IBSRP Health",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Alert State" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select binary_state from services where title='ddn-ibsrp' and $timeFilter GROUP BY host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "iptables Health",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Alert State" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select binary_state from services where title='iptables' and host =~ /your_nsd_server_regex[1-6].*/ and  $timeFilter GROUP BY host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mount Health",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Mount Presence" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_fs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select presence from mountcheck where host =~ /^your_nsd_server_regex[1-6].*/ and $timeFilter GROUP BY host,fs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deadlock Check",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Deadlock Present",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select deadlock from deadlock_detect where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Host Specific Metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Local Disk Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select used_percent from disk where $timeFilter and  host =~ /$host$/ and fstype != 'gpfs'  and fstype != 'iso9660' GROUP BY path",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inbound Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(\"bytes_recv\", 1m) FROM \"autogen\".\"net\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter  group by \"interface\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outbound Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(\"bytes_sent\", 1m) FROM \"autogen\".\"net\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter  group by \"interface\"",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Processes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select total from processes where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zombie Processes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select zombies from processes where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(uptime) from system where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Interface Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select err_in from net where $timeFilter and host =~ /$host$/ GROUP BY interface",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_interface TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select err_out from net where $timeFilter and host =~ /$host$/ GROUP BY interface",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select usage_idle from cpu where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select usage_system from cpu where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select usage_user from cpu where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "IO Wait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select usage_iowait from cpu where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1 Minute Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select load1 from system where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "5 Minute Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select load5 from system where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "15 Minute Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select load15 from system where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPFS Waiter Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Waiters",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count from waitercount where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Longest GPFS Waiter Length",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "Longest Waiter Length",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select length from longestwaiter where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IB Symbol Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select symbol_error from infiniband where $timeFilter and host =~ /$host$/ group by device",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select used_percent from mem where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select available_percent from mem where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPFS Daemon CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Used by mmfsd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select usage from daemoncpu where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPFS Daemon Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory Used by mmfsd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select usage from daemonmem where $timeFilter and host =~ /$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}